name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
  
  
jobs:


  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest    
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: 0xCAF3D0OD
          template: classic
          base: header
          config_timezone: Europe/Zurich
          
  metrics:
    permissions:
      contents: write
      steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"

  Repositories_diff_history:
      permissions: write-all
      runs-on: ubuntu-latest
      steps:
        - uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.lines.history.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_lines: yes
            plugin_lines_sections: repositories, history
            plugin_lines_repositories_limit: 2
            plugin_lines_history_limit: 1
