name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}

jobs:
  github-metrics:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      - name: Base
        uses: lowlighter/metrics@latest    
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: 0xCAF3D0OD
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Zurich     

      - name: metrics classic
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          
      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

#       - name: Metrics
#         uses: lowlighter/metrics@latest
#         with:
#            token: ${{ secrets.METRICS_TOKEN }}
#            output_action: commit
#            committer_branch: metrics-renders
#            committer_message: "chore: update metrics"

      - name: Repositories diff history
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.lines.history.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_lines: yes
            plugin_lines_sections: repositories, history
            plugin_lines_repositories_limit: 2
            plugin_lines_history_limit: 1

      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.habits.charts.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_habits: yes
            plugin_habits_facts: no
            plugin_habits_charts: yes
            config_timezone: Europe/Zurich
            
      - name: Detailed report
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://lecoq.io

      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_languages_other: yes
          plugin_wakatime_user: kdi_noce

      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

  
#       - name: Most used
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.languages.svg
#           token: ${{ secrets.METRICS_TOKEN }}
#           base: ""
#           plugin_languages: yes
#           plugin_languages_ignored: >-
#             html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
#             gnuplot
#           plugin_languages_limit: 4
    
#       - name: Indepth analysis
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.languages.indepth.svg
#           token: ${{ secrets.METRICS_TOKEN }}
#           base: ""
#           plugin_languages: yes
#           plugin_languages_sections: most-used
#           plugin_languages_indepth: yes
#           plugin_languages_categories: programming
#           plugin_languages_colors: github
#           plugin_languages_threshold: 0%
#           plugin_languages_details: percentage


